name: flutter_application_1
description: A new Flutter project to capture image from camera or gallery.

# Versi SDK Flutter yang digunakan
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  image_picker: ^1.1.1

  # Kamu bisa tambahkan paket lain di bawah ini jika perlu
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2

  #image_picker_for_web: ^3.1.0
  #camera_web: ^0.3.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true